config/routes.rb
Rails.application.routes.draw do
  get 'university/index'
  get 'university/refresh_data'
  root to: "university#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/university_controller.rb
class UniversityController < ApplicationController
  def index
    params[:page] = params[:page] || 1
    @data = File.read(Rails.configuration.data_dir.join("university_record.json")) rescue nil
    if @data
      @records = Kaminari.paginate_array(JSON.parse(@data)["data"]).page(params[:page]).per(10)
    end
  end

  def refresh_data
    Cialfo::Application.load_tasks
    Rake::Task["university:scrap_detail"].invoke
  end
end

app/helpers/university_helper.rb
module UniversityHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cialfo</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/university/index.html.erb
<h1 class="data_display">List of University</h1>
<div class="data_display page_entry_info">
  <%= page_entries_info @records, :entry_name => 'Universities' %>
</div>

<%= link_to "Refresh", university_refresh_data_path , :class=>"btn btn-primary refresh_button pull-right", :remote => true,"data-disable-with"=>"Processing" %>

<table class="table table-striped table-bordered data_display">
  <thead>
  <tr>
    <th>Rank</th>
    <th>School Name</th>
    <th>Tuition fees</th>
    <th>Total enrollment</th>
    <th>Acceptance rate</th>
    <th>Retention rate</th>
    <th>Graduation rate</th>
  </tr>
  </thead>
  <tbody>
  <% @records.each do |value| %>
      <tr>
        <td><%= value["rank"]  %></td>
        <td><%= value["name"]  %></td>
        <td><%= value["tuition_fees"]  %></td>
        <td><%= value["total_enrollment"]  %></td>
        <td><%= value["acceptance_rate"]  %></td>
        <td><%= value["average_retention_rates"] %></td>
        <td><%= value["graduation_rate"] %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<div class="data_display">
  <%= paginate @records %>
</div>

app/views/university/refresh_data.js.erb
alert("Data Loaded");